### ISSUE TITLE
Can't compile on a Mac OS X 10.5 (u_int, u_long and u_char undefined)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [archiecobbs/s3backer#1]
```
What steps will reproduce the problem?
1. Download, unpack. 
2. ./configure
3. make
4. Make shows errors (below).

I am on a Mac OS X 10.5

If add lines:

typedef unsigned int u_int;
typedef unsigned long u_long;
typedef unsigned char u_char;

to s3backer.h everything compiles Ok.

Original make errors:

In file included from main.c:25:
s3backer.h:84: error: syntax error before ‘u_int’
s3backer.h:84: warning: no semicolon at end of struct or union
s3backer.h:85: warning: type defaults to ‘int’ in declaration of 
‘block_bits’
s3backer.h:85: warning: data definition has no type or storage class
s3backer.h:89: error: syntax error before ‘connect_timeout’
s3backer.h:89: warning: type defaults to ‘int’ in declaration of
‘connect_timeout’
s3backer.h:89: warning: data definition has no type or storage class
s3backer.h:90: error: syntax error before ‘io_timeout’
s3backer.h:90: warning: type defaults to ‘int’ in declaration of 
‘io_timeout’
s3backer.h:90: warning: data definition has no type or storage class
s3backer.h:91: error: syntax error before ‘initial_retry_pause’
s3backer.h:91: warning: type defaults to ‘int’ in declaration of
‘initial_retry_pause’
s3backer.h:91: warning: data definition has no type or storage class
s3backer.h:92: error: syntax error before ‘max_retry_pause’
s3backer.h:92: warning: type defaults to ‘int’ in declaration of
‘max_retry_pause’
s3backer.h:92: warning: data definition has no type or storage class
s3backer.h:93: error: syntax error before ‘min_write_delay’
s3backer.h:93: warning: type defaults to ‘int’ in declaration of
‘min_write_delay’
s3backer.h:93: warning: data definition has no type or storage class
s3backer.h:94: error: syntax error before ‘cache_time’
s3backer.h:94: warning: type defaults to ‘int’ in declaration of 
‘cache_time’
s3backer.h:94: warning: data definition has no type or storage class
s3backer.h:95: error: syntax error before ‘cache_size’
s3backer.h:95: warning: type defaults to ‘int’ in declaration of 
‘cache_size’
s3backer.h:95: warning: data definition has no type or storage class
s3backer.h:97: warning: built-in function ‘log’ declared as non-function
s3backer.h:102: error: syntax error before ‘}’ token
s3backer.h:132: error: syntax error before ‘u_int’
s3backer.h:132: warning: function declaration isn’t a prototype
main.c: In function ‘main’:
main.c:41: error: dereferencing pointer to incomplete type
main.c:41: error: ‘u_long’ undeclared (first use in this function)
main.c:41: error: (Each undeclared identifier is reported only once
main.c:41: error: for each function it appears in.)
main.c:41: error: syntax error before ‘getpid’
main.c:42: error: dereferencing pointer to incomplete type
main.c:42: error: dereferencing pointer to incomplete type
make[1]: *** [main.o] Error 1
make: *** [all] Error 2

```

Original issue reported on code.google.com by `dimaulu...@gmail.com` on 9 Jul 2008 at 4:19
